### Makefile

LISP=./lisp.py
LIBS=../lisp/stdlib.lisp ../lisp/runtime.lisp ../lisp/cont.lisp

run:
	$(LISP) $(LIBS) -

bench:
	time $(LISP) $(LIBS) ../bench.lisp

sicp:
	$(LISP) $(LIBS) ../sicp.lisp

## EOF
